### PR TITLE
Remove unnecessary artefacts after building lua

### PR DESCRIPTION
**Pull request by sobrinho**
This pull request combines all build steps in one step and removes the used packages right after compiling.

The final image got reduced from 332MB to 135.7MB.

### CODE REVIEW

**Comment by sobrinho** [comment]
I would be happy to maintain this docker image and propose it as official image for lua if you like.

**Comment by niaquinto** [comment]
As with any open source repo, you're welcome to fork. I'm at work at the moment, but I'll be able to merge this later in a couple hours.

**Comment by niaquinto** [comment]
Ok, now that I've had a chance to actually look at what this is, I'd like to challenge your argument that a lua container shouldn't have curl, git, and standard build dependencies. Look at the [ruby](https://github.com/docker-library/ruby/blob/d67b6c0361aa2aceb4f9bc3fd155000584490a10/2.2/Dockerfile), [python](https://github.com/docker-library/python/blob/5fc2d82f706e338286f31908ef416afe7b5fba7b/3.4/Dockerfile), [node.js](https://github.com/joyent/docker-node/blob/787d816f90dc1bf933b6503b876bdeb752b24f96/0.12/Dockerfile), and other basic language containers; they are all are based on [buildpack-deps](https://hub.docker.com/_/buildpack-deps/), too.

I don't think that I'm alone in expecting a `pip intsall`, `npm install`, or `gem install` to Just Work™. If anything, I'd rather go the opposite direction and include luarocks in this image.

Nevertheless, you're right about upgrading the container. And, we could get away with using `buildpack-deps:jessie` instead of `buildpack-deps:jessie-scm`, which would remove git.

**Comment by sobrinho** [comment]
We could keep these packages but I don't think we should. If we need any of them, we can create a new image based on this one and install what we need, don't you think?

In my use case, I have mathematical lua scripts running with zeromq which doesn't need anything besides lua itself, why pay the price to have these packages?

Take a look at the [ruby-slim](https://github.com/docker-library/ruby/blob/d67b6c0361aa2aceb4f9bc3fd155000584490a10/2.2/slim/Dockerfile) image which is the recommended for production, they do use debian:jessie and only install needed packages.

I could say that they left some packages that is not really needed in fact, not sure why they did that.

About luarocks, I think it makes perfect sense to be on this image itself instead of another one since it will be used for almost 99% of the time.

Reference: https://docs.docker.com/articles/dockerfile_best-practices/#avoid-installing-unnecessary-packages

**Comment by niaquinto** [comment]
Just pushed 830edd6e2fbd8f686a8d26754644d1e25b02b4a0, which adds a slim version image as included in your pull request.

Also, I've updated the wheezy and jessie versions of the image to not upgrade and to remove build dependencies after use.

So, now you can pull & use `5.2`, `5.2.4`, `5.2-wheezy`, `5.2.4-wheezy`, `5.2-jessie`, `5.2.4-jessie`, `5.2-slim`, and `5.2.4-slim`. And, they're much smaller images.

I'll add luarocks to the non-slim images later today.

**Comment by sobrinho** [comment]
Nice, thanks!

**Pull request closed without merging**
